apiVersion: apps/v1
kind: Deployment
metadata:
  name: marketfeed
  namespace: stocksim
spec:
  replicas: 1
  selector: { matchLabels: { app: marketfeed } }
  template:
    metadata: { labels: { app: marketfeed } }
    spec:
      containers:
      - name: api
        image: stocksim-marketfeed:k8s
        imagePullPolicy: IfNotPresent
        ports: [{ containerPort: 8080, name: http }]
        env:
        - name: ASPNETCORE_URLS
          value: http://+:8080
        readinessProbe:
          httpGet: { path: /readyz, port: 8080 }
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          httpGet: { path: /healthz, port: 8080 }
          initialDelaySeconds: 5
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: marketfeed
  namespace: stocksim
spec:
  selector: { app: marketfeed }
  ports:
  - name: http
    port: 8080
    targetPort: 8080
